import jwt from 'jsonwebtoken'
import BLOG from '../models/Blog.js';
import COMMENT from '../models/Comments.js';

export const adminLogin = async(req , res) =>{
    try{
        const {email , password} = req.body;

        if(email !== process.env.ADMIN_EMAIL || password !== process.env.ADMIN_PASSWORD){
            return res.json({success:false , message:'Invalid Credentials'})
        }

        const token = jwt.sign({email} , process.env.JWT_SECRET)
        res.json({success:true , token})
    }catch(error){
        res.json({success:false , message:error.message})
    }
}



export const getAllBlogsAdmin = async(req,res)=>{
    try{
        const blogs = await BLOG.find({}).sort({createdAt:-1});
        return res.json({success:true , blogs})
    }catch(error){
        return res.json({success:false , message:error.message})
    }
}



export const getAllComments = async(req,res) =>{
    try{
        const comments = await COMMENT.find({}).populate("blog").sort({createdAt:-1});
        return res.json({success:true , comments})
    }catch(error){
        return res.json({success:false , message:error.message})
    }
}




export const getDashboard = async(req,res) =>{
    try{
        const recentBlogs = await BLOG.find({}).sort({createdAt:-1}).limit(5);
        const blogs = await BLOG.countDocuments();
        const comments = await COMMENT.countDocuments();
        const drafts = await BLOG.countDocuments({isPublished:false})

        const dashboardData = { recentBlogs , blogs , comments , drafts }

        return res.json({success:true , dashboardData})
    }catch(error){
        return res.json({success:false , message:error.message})
    }
}

// New - return basic DB stats to help debugging
export const getDBStats = async(req,res) =>{
    try{
        const blogs = await BLOG.countDocuments();
        const comments = await COMMENT.countDocuments();
        const recent = await BLOG.find({}).sort({createdAt:-1}).limit(1);
        return res.json({success:true, blogs, comments, recent: recent[0] || null});
    }catch(error){
        return res.status(500).json({success:false, message:error.message});
    }
}

// Admin-only seeder route - creates a sample published blog and an approved comment
export const seedDatabase = async (req, res) => {
    try{
        const force = req.query.force === '1' || req.query.force === 'true';
        const existing = await BLOG.countDocuments();
        if(existing > 0 && !force){
            return res.json({success:false, message: 'Database already has data. Use ?force=1 to force seeding.'});
        }

        const sampleBlog = await BLOG.create({
            title: 'Sample Seeded Blog',
            subTitle: 'This blog was generated by seeder',
            description: '<p>This is a sample blog seeded for testing purposes.</p>',
            category: 'Technology',
            image: process.env.IMAGE || 'https://www.atulhost.com/wp-content/uploads/2017/10/blog.jpg',
            isPublished: true
        });

        await COMMENT.create({ blog: sampleBlog._id, name: 'Seeder', content: 'This is a seeded comment', isApproved: true });

        return res.json({success:true, message:'Seeding completed', sampleBlog});
    }catch(error){
        console.error('Error in seedDatabase:', error);
        return res.status(500).json({success:false, message:error.message});
    }
}


export const deleteCommentById = async(req,res) =>{
    try{
        const { id } = req.body;
        await COMMENT.findByIdAndDelete(id);
        return res.json({success:true})
    }catch(error){
        return res.json({success:false , message:error.message})
    }
}


export const approveCommentById = async(req,res) =>{
    try{
        const { id } = req.body;
        await COMMENT.findByIdAndUpdate(id , {isApproved:true});
        return res.json({success:true , message:"Comment Approved"});
    }catch(error){
        return res.json({success:false , message:error.message})
    }
}